meta_title: "Fluicity"
meta_description: "Fluicity is a turn-key technology and data management platform allowing cities to easily involve citizen into local decisions."
meta_image: "cards/fluicity-social-card.jpg"